pipeline:
  name: OpenAI Plugin Example
  identifier: openai_plugin_example
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Call OpenAI
        identifier: Call_OpenAI
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Call OpenAI
                  identifier: Call_OpenAI
                  spec:
                    connectorRef: account.harnessImage
                    image: yourusername/drone-openai-plugin:latest
                    settings:
                      api_key: <+secrets.getValue("openai_api_key")>
                      prompt: Describe New York's weather as a Haiku
